[project]
name = "cmeel-tinyxml"
version = "2.6.2"
description = "cmeel distribution for TinyXML, an obsolete thing."
readme = "README.md"
requires-python = ">= 3.8"
license = "Zlib"

[project.urls]
homepage = "https://github.com/cmake-wheel/cmeel-tinyxml"

[build-system]
requires = ["cmeel[build]"]
build-backend = "cmeel.build"
run-tests = false
